gsap.registerPlugin(ScrollTrigger) //Gsap scroll trigger plugin

const vw = window.innerWidth;

const moveFront = -vw * 0.71;
const moveBack = vw * 0.52;
const moveHead = -vw * 0.27;
const moveTextAI = -vw * 0.71;

function disableScroll() {

    document.body.style.overflow = "hidden";

    window.addEventListener("wheel", preventScroll, { passive: false });
    window.addEventListener("touchmove", preventScroll, { passive: false });
    window.addEventListener("keydown", preventKeys);

}

function enableScroll() {

    document.body.style.overflow = "";

    window.removeEventListener("wheel", preventScroll);
    window.removeEventListener("touchmove", preventScroll);
    window.removeEventListener("keydown", preventKeys);

}

function preventScroll(e) {
    e.preventDefault();
}

function preventKeys(e) {

    const keys = [
        "ArrowUp",
        "ArrowDown",
        "ArrowLeft",
        "ArrowRight",
        "PageUp",
        "PageDown",
        "Home",
        "End",
        " ",
    ];

    if (keys.includes(e.key)) {
        e.preventDefault();
    }
}

gsap.from(".robot-head", {
    x: 200,
    opacity: 0,
    duration: 1.5,
    ease: "power2.out",
    clearProps: "transform",

    onComplete: () => {
        enableScroll();

        ScrollTrigger.refresh();

        createRobotTimeline();
    }
});

disableScroll();

function createRobotTimeline() {

    let scrollEnd = "+=1900";

    /*for 4K */
    if (window.innerWidth >= 1440) {
        scrollEnd = "+=3000";
    }

    let tl = gsap.timeline({
        scrollTrigger: {
            trigger: "body",
            start: "top top",
            end: scrollEnd,
            scrub: 2,
            pin: ".robot-head"
        }
    });

    // Robot and text animations
    tl.to(".robot-front", {
        x: moveFront,
        y: 45,
        duration: 2
    });

    tl.to(".robot-back", {
        x: moveBack,
        y: -280,
        duration: 2
    }, "<");

    tl.to(".robot-head", {
        x: moveHead,
        duration: 1
    }, "<");

    tl.to(".text-ai", {
        x: moveTextAI,
        y: 145,
        duration: 1
    }, "<");

    tl.to(".text-ml", {
        opacity: 1,
        duration: 1.2
    }, "<");

    // Brain flicker
    tl.to(".robot-brain-f", { opacity: 1, duration: 0.1 }, "<0.2");
    tl.to(".robot-brain-m", { opacity: 1, duration: 0.1 }, "<0.1");
    tl.to(".robot-brain-b", { opacity: 1, duration: 0.1 }, "<0.1");
    tl.to(".text-ml", { opacity: 1, duration: 0.3 }, "<");

    // Brain movement
    tl.to(".robot-brain-f", {
        x: -50,
        y: 20,
        duration: 1
    });

    tl.to(".robot-brain-m", {
        y: -20,
        duration: 1
    }, "<");

    tl.to(".robot-brain-b", {
        x: 80,
        y: -30,
        duration: 1
    }, "<");

    tl.to(".text-ml", { opacity: 1, duration: 1 }, "<");
    tl.to(".text-ml", { opacity: 0, duration: 1 }, "<");

    tl.to(".super", { opacity: 1, duration: 1 }, "<");
    tl.to(".unsuper", { opacity: 1, duration: 1 }, "<");
    tl.to(".reinforce", { opacity: 1, duration: 1 }, "<");

    // Glow ray

    tl.to(".glow-ray-m", {
        height: 1000,
        duration: 0.8
    }, "<");

    const musicSwitch = document.querySelector('.switch'); // Music toggle switch
    const bgMusic = document.querySelector('.bgMusic'); // Background music audio element to trigger the audio

    // The below code is generated by claude AI:-

    // Note: Most browsers block autoplay until user interact so I had to make the default switch as OFF rather than ON

    // Listen for switch changes
    if (musicSwitch && bgMusic) {
        musicSwitch.addEventListener('sl-change', (e) => {
            if (e.target.checked) {
            bgMusic.play();
            } else {
            bgMusic.pause();
            }
        });
    }

    const shoeButton = document.querySelector('.shoe-button');
    const blackBelow = document.querySelector('.black-below');
    const carouselContainer = document.querySelector('.carousel-container');
    const carousel = document.querySelector('.carousel-thumbnails');
    const thumbnails = document.querySelectorAll('.thumbnails__image');

    shoeButton.addEventListener('click', () => {
        blackBelow.classList.add('show');
        carouselContainer.classList.add('show');
    });

    document.addEventListener('keydown', (e) => {
        if (!carouselContainer.classList.contains('show')) return;

        if (e.key === 'ArrowLeft') {
            carousel.previous();
        }

        if (e.key === 'ArrowRight') {
            carousel.next();
        }

    });

    document.addEventListener('keydown', (e) => {
        if (e.key === 'Escape') {
            blackBelow.classList.remove('show');
            carouselContainer.classList.remove('show');
        }
    });

    blackBelow.addEventListener('click', () => {
        blackBelow.classList.remove('show');
        carouselContainer.classList.remove('show');
    });

    thumbnails.forEach((thumbnail, index) => {

        thumbnail.addEventListener('click', () => {

            carousel.goToSlide(index);

        });

    });

    function updateActiveThumbnail(index) {

        thumbnails.forEach((thumb) => {
            thumb.classList.remove('active');
        });

        thumbnails[index].classList.add('active');

    }

    thumbnails.forEach((thumbnail, index) => {

        thumbnail.addEventListener('click', () => {

            carousel.goToSlide(index);

            updateActiveThumbnail(index);

        });
    });

    carousel.addEventListener('sl-slide-change', (event) => {

        updateActiveThumbnail(event.detail.index);

    });

    // The rest of your page scroll/navigation code remains the same
    const pages = [
    document.querySelector('.Intro-content'),
    document.querySelector('.page-two'),
    document.querySelector('#page-three'),
    document.querySelector('#page-four'),
    document.querySelector('#page-five')
    ]; // this sets all the content pages into arrays which we can easily loop around

    let currentIndex = 0; //sets the 1st page index value as 0

    function scrollToPage(index) { // Sets a condition for function for scrolltopage
    if (index >= 0 && index < pages.length) { // If function. this basically sets some conditions before any action begins. index >=0 means to sure the number isn’t negative. index < pages.length ensures it is less than the total number of pages
        pages[index].scrollIntoView({ behavior: 'smooth' }); // If the above conditions are met, only then run this code. scrollIntoView brings scroll element into view. behaviour-smooth ensures realistic scroll behaviour
        currentIndex = index; // Updates index with new page
        updateButtonState(); // changes the behaviour of back and next button
    }
    }

    function updateButtonState() { // Making backward forward buttons functionable
    const backButton = document.querySelector('.backward-button'); // Setting it as const
    const forwardButton = document.querySelector('.forward-button'); // Setting it as const

    backButton.disabled = currentIndex === 0; // When the current index is 0 (meaning we are at the landing page), the backward button is disabled
    forwardButton.disabled = currentIndex === pages.length - 1; //Same here
    }

    document.querySelector('.forward-button').addEventListener('click', () => { // Adding events to navigation button forward
    if (currentIndex < pages.length - 1) { // If function here. it says that run the code only when this condition is met- Check if you’re not on the last page yet.
        scrollToPage(currentIndex + 1); // Moves to the next page smoothly.
    }
    });

    document.querySelector('.backward-button').addEventListener('click', () => { // Adding for navigation button backward
    if (currentIndex > 0) { // If current index is not 0. Means it only works if you're not on first page
        scrollToPage(currentIndex - 1); // Scroll one page back (-1) when clicked
    }
    });

    window.addEventListener('scroll', () => { // An event listener for scroll
    pages.forEach((page, index) => { // goes through each page in pages array
        const rect = page.getBoundingClientRect(); // Realise the page’s position on the screen
        if (rect.top >= 0 && rect.top < window.innerHeight / 2) { // If the top of that page is somewhere in the top half of the screen, that means this is the page currently being viewed.
        currentIndex = index; 
        updateButtonState(); // Updates the current page number
        }
    });
    });

    updateButtonState(); // Runs once at the start to make sure the buttons are correctly set when the page first loads.
}

